/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'eyes' : IDL.Null,
  'face' : IDL.Null,
  'lips' : IDL.Null,
  'skincare' : IDL.Null,
});
export const Time = IDL.Int;
export const MakeupLook = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'created' : Time,
  'creator' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'likes' : IDL.Nat,
  'category' : Category,
});
export const Tutorial = IDL.Record({
  'title' : IDL.Text,
  'duration' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addLook' : IDL.Func(
      [IDL.Text, Category, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'getAllLooks' : IDL.Func([], [IDL.Vec(MakeupLook)], ['query']),
  'getAllTutorials' : IDL.Func([], [IDL.Vec(Tutorial)], ['query']),
  'getLooksByCategory' : IDL.Func([Category], [IDL.Vec(MakeupLook)], ['query']),
  'likeLook' : IDL.Func([IDL.Nat], [], []),
  'searchLooksByTag' : IDL.Func([IDL.Text], [IDL.Vec(MakeupLook)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'eyes' : IDL.Null,
    'face' : IDL.Null,
    'lips' : IDL.Null,
    'skincare' : IDL.Null,
  });
  const Time = IDL.Int;
  const MakeupLook = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'created' : Time,
    'creator' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'likes' : IDL.Nat,
    'category' : Category,
  });
  const Tutorial = IDL.Record({ 'title' : IDL.Text, 'duration' : IDL.Nat });
  
  return IDL.Service({
    'addLook' : IDL.Func(
        [IDL.Text, Category, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'getAllLooks' : IDL.Func([], [IDL.Vec(MakeupLook)], ['query']),
    'getAllTutorials' : IDL.Func([], [IDL.Vec(Tutorial)], ['query']),
    'getLooksByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(MakeupLook)],
        ['query'],
      ),
    'likeLook' : IDL.Func([IDL.Nat], [], []),
    'searchLooksByTag' : IDL.Func([IDL.Text], [IDL.Vec(MakeupLook)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };